
import React, { useState, useEffect } from 'react';
import { db } from '../../services/dataService';
import { Job, AdminInstruction, Priority, Staff, JobStatusDefinition } from '../../types';
import { AlertCircle, Clock, Plus, Loader2 } from 'lucide-react';
import { JobStatusItem } from './JobStatusItem';
import { InstructionPanel } from './InstructionPanel';
import { useAuth } from '../../contexts/AuthContext';
import { useDialog } from '../../contexts/DialogContext';
import { JobDetailModal } from '../common/JobDetailModal';
import { ClientContactModal } from '../common/ClientContactModal';

interface DashboardProps {
  onNavigateToQuote: (quoteId?: string) => void;
}

export const Dashboard: React.FC<DashboardProps> = ({ onNavigateToQuote }) => {
  const [jobs, setJobs] = useState<Job[]>([]);
  const [staff, setStaff] = useState<Staff[]>([]);
  const [instructions, setInstructions] = useState<AdminInstruction[]>([]);
  const [statusDefinitions, setStatusDefinitions] = useState<JobStatusDefinition[]>([]);
  const { currentUser } = useAuth();
  const { showConfirm } = useDialog();
  const [selectedJob, setSelectedJob] = useState<Job | null>(null);
  const [contactingJob, setContactingJob] = useState<Job | null>(null);
  const [isCreatingJob, setIsCreatingJob] = useState(false);

  const loadData = () => {
    // Performance Optimization: Only load Active Jobs for Dashboard
    setJobs(db.getActiveJobs());
    setInstructions(db.getInstructions());
    setStaff(db.getStaff());
    setStatusDefinitions(db.getStatusDefinitions());
  };

  useEffect(() => {
    loadData();
    // Subscribe to DB changes (Real-time updates)
    const unsubscribe = db.subscribe(() => {
        loadData();
    });
    return () => unsubscribe();
  }, []);

  const handleAddInstruction = (content: string, important: boolean) => {
    const newInst: AdminInstruction = {
      id: Date.now().toString(),
      content,
      date: new Date().toISOString(),
      important: important
    };
    // Safe update via DB service
    db.saveInstructions([newInst, ...instructions]);
  };

  const deleteInstruction = async (id: string) => {
    if (await showConfirm('이 지시사항을 삭제하시겠습니까?')) {
        db.deleteInstruction(id);
    }
  };

  const handleUpdateJob = (updated: Job) => {
    // Use the smart update method in DB
    db.updateJob(updated);
    // UI will auto-update via subscription, but we can close modal immediately
    setSelectedJob(null);
  };

  const handleCreateJob = (newJob: Job) => {
    db.addJob(newJob);
    // UI will auto-update
    setIsCreatingJob(false);
  }

  // Helper: Sort jobs strictly by Priority then Due Date
  const sortedJobs = [...jobs].sort((a, b) => {
    // 1. Sort by Priority (Very Urgent > Urgent > Normal)
    const prioScore = { [Priority.VERY_URGENT]: 3, [Priority.URGENT]: 2, [Priority.NORMAL]: 1 };
    if (prioScore[a.priority] !== prioScore[b.priority]) {
      return prioScore[b.priority] - prioScore[a.priority]; // Descending score
    }
    
    // 2. Sort by Due Date (Sooner first)
    return new Date(a.dueDate).getTime() - new Date(b.dueDate).getTime();
  });

  // Empty template for new job
  const emptyJob: Job = {
    id: '', // Will be generated by db.addJob
    title: '',
    clientName: '',
    description: '',
    specs: {
      paperType: '', // Allow dynamic default in Modal
      paperWeight: '',
      size: '',
      quantity: '',
      processing: [],
      printColor: '단면 4도(컬러)', // Default to Color
      memo: ''
    },
    status: statusDefinitions.length > 0 ? statusDefinitions[0].key : 'RECEIVED',
    priority: Priority.NORMAL,
    paymentStatus: '결제대기',
    createdAt: new Date().toISOString(),
    dueDate: new Date(Date.now() + 86400000).toISOString(),
    progress: 0,
    type: db.getJobTypes()[0] || '기타', // Dynamic Type
    price: 0,
    order: 0
  };

  return (
    <div className="flex flex-col lg:flex-row h-full gap-4 lg:gap-6 overflow-hidden relative">
      {/* Main Area: Job Status Board */}
      <div className="flex-1 flex flex-col min-w-0 bg-white dark:bg-slate-800 rounded-xl shadow-sm border border-slate-200 dark:border-slate-700 overflow-hidden transition-colors">
        {/* Header */}
        <div className="p-3 lg:p-4 border-b border-slate-200 dark:border-slate-700 bg-slate-50 dark:bg-slate-850 flex justify-between items-center flex-none">
          <div className="flex items-center gap-4">
            <div>
              <h2 className="text-lg lg:text-xl font-bold text-slate-800 dark:text-slate-100 flex items-center gap-2">
                <span className="w-2 lg:w-3 h-6 lg:h-8 bg-gradient-to-b from-red-500 to-blue-600 rounded-sm"></span>
                실시간 작업 상황판
              </h2>
            </div>
          </div>
          <div className="flex gap-2 items-center">
             <div className="hidden sm:flex gap-2 text-xs lg:text-sm font-medium mr-2">
               <div className="flex items-center gap-1.5 px-2 py-1 bg-red-50 dark:bg-red-900/30 text-red-700 dark:text-red-300 rounded-lg border border-red-100 dark:border-red-800">
                  <AlertCircle size={14} />
                  <span>긴급: {jobs.filter(j => j.priority !== Priority.NORMAL).length}</span>
               </div>
               <div className="flex items-center gap-1.5 px-2 py-1 bg-blue-50 dark:bg-blue-900/30 text-blue-700 dark:text-blue-300 rounded-lg border border-blue-100 dark:border-blue-800">
                  <Clock size={14} />
                  <span>진행: {jobs.filter(j => j.status !== 'DELIVERY').length}</span>
               </div>
             </div>
             
             <button 
               onClick={() => setIsCreatingJob(true)}
               title="새로운 작업을 등록합니다"
               className="bg-blue-600 hover:bg-blue-700 text-white px-3 py-1.5 rounded-lg text-sm font-bold flex items-center gap-1 shadow-sm transition-all hover:scale-105"
             >
               <Plus size={18} />
               <span className="hidden sm:inline">작업 등록</span>
               <span className="sm:hidden">등록</span>
             </button>
          </div>
        </div>

        {/* List Content */}
        <div className="flex-1 overflow-y-auto p-3 space-y-2 bg-slate-50/50 dark:bg-slate-900/50 custom-scrollbar">
          {sortedJobs.length === 0 && (
             <div className="flex flex-col items-center justify-center h-full text-slate-400">
                <p>현재 진행 중인 작업이 없습니다.</p>
                <button onClick={() => setIsCreatingJob(true)} className="mt-2 text-blue-600 hover:underline" title="작업 등록하기">새 작업 등록하기</button>
             </div>
          )}
          {sortedJobs.map((job) => {
             const isMyJob = currentUser && job.assignedStaffId === currentUser.id;
             return (
               <div 
                 key={job.id} 
                 className={`${isMyJob ? "relative" : ""} cursor-pointer`}
                 onClick={() => setSelectedJob(job)}
                 title="클릭하여 상세 정보 보기"
               >
                 {isMyJob && (
                   <div className="absolute -left-1 top-2 bottom-2 w-1 bg-blue-600 rounded-r-md z-10 shadow-sm"></div>
                 )}
                 <JobStatusItem 
                  job={job} 
                  staff={staff} 
                  statusDefinitions={statusDefinitions}
                  onContact={(j) => setContactingJob(j)}
                 />
               </div>
             );
          })}
        </div>
      </div>

      {/* Side Panel: Admin Instructions - Hidden on Mobile */}
      <div className="hidden lg:flex w-full lg:w-72 xl:w-80 2xl:w-96 flex-col gap-6 flex-none pb-24 lg:pb-24 transition-all duration-300">
        <InstructionPanel 
          instructions={instructions} 
          onAdd={handleAddInstruction} 
          onDelete={deleteInstruction} 
        />
      </div>

      {selectedJob && (
        <JobDetailModal 
          job={selectedJob} 
          staff={staff} 
          onClose={() => setSelectedJob(null)} 
          onUpdate={handleUpdateJob}
          onNavigateToQuote={onNavigateToQuote}
        />
      )}
      
      {isCreatingJob && (
        <JobDetailModal 
          job={emptyJob}
          staff={staff}
          onClose={() => setIsCreatingJob(false)}
          onUpdate={handleCreateJob}
          isNew={true}
        />
      )}

      {contactingJob && (
        <ClientContactModal 
          job={contactingJob} 
          onClose={() => setContactingJob(null)} 
        />
      )}
    </div>
  );
};
